---

- name: Copy requirements to remote host
  copy:
    src: files/requirements.txt
    dest: /tmp/requirements.txt
    mode: '0755'

- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: /tmp/requirements.txt

- name: Create ml Directory if Not Exist
  become: true
  file:
    path: /data/ml
    state: directory
    mode: '0755'
  tags:
    - mlapp

- name: Copy ml job to ml directory 
  copy:
    src: files/image_train.py
    dest: /data/ml/image_train.py
    mode: '0755'
  tags:
    - mlapp
